---
driver:
    name: hyperv
    memory_startup_bytes: 2147483648
    dynamic_memory: true
    vm_switch: "'Hyper-V'"

provisioner:
  name: chef_zero
  roles_path: '../roles'

transport:
  name: winrm
  elevated: true
  password: 'vagrant'
  username: 'vagrant'

platforms:
  - name: win-10
    os_type: windows
    driver:
        parent_vhd_folder: '../../.output/hyperv/win10/Virtual Hard Disks'
        parent_vhd_name: 'win10.vhdx'
#  - name: server-2016
#    os_type: windows
#    driver:
#        parent_vhd_folder: '../../.output/hyperv/server-2016'
#        parent_vhd_name: 'win-server-2016.vhdx'

verifier:
      name: inspec

suites:
  - name: common
    run_list:      
#      - recipe[packer-windows::install_ps_nuget_provider]
#      - recipe[packer-windows::allow_rdp]
#      - recipe[packer-windows::enable_file_sharing]
#      - recipe[packer-windows::set_local_account_token_filter_policy]
#      - recipe[packer-windows::add_sysprep_unattended]
#      - recipe[packer-windows::disable_cortana]
#      - recipe[packer-windows::uninstall_one_drive]
#      - recipe[packer-windows::uninstall_windows_media_player]
#      - recipe[packer-windows::clean_sxs]
      - role[dotnet_env]
    attributes: 
        box_settings:
            username: 'kitchen-username'
            user_password: 'kitchen-password'
            time_zone: 'kitchen-time_zone'
            locale: 'kitchen-locale'
            user_description: 'kitchen-user_description'